// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UniConnect.Infrastructure.Data;

#nullable disable

namespace UniConnect.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260520145701_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UniConnect.Delivery.Entities.BusinessAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FleetId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FleetId", "AccountCode")
                        .IsUnique();

                    b.ToTable("BusinessAccounts");
                });

            modelBuilder.Entity("UniConnect.Delivery.Entities.DeliveryAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AutomationMode")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeliveryOrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryOrderId")
                        .IsUnique();

                    b.ToTable("DeliveryAssignments");
                });

            modelBuilder.Entity("UniConnect.Delivery.Entities.DeliveryOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BusinessAccountId")
                        .HasColumnType("uuid");

                    b.Property<int>("Channel")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FleetId")
                        .HasColumnType("uuid");

                    b.Property<string>("ParcelDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PickupAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecipientPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ScheduledWindowEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ScheduledWindowStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BusinessAccountId");

                    b.ToTable("DeliveryOrders");
                });

            modelBuilder.Entity("UniConnect.Domain.Entities.Fleet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FleetType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Fleets");
                });

            modelBuilder.Entity("UniConnect.Domain.Entities.MaintenanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric");

                    b.Property<int>("MileageAtService")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("PerformedOn")
                        .HasColumnType("date");

                    b.Property<int>("ServiceType")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("MaintenanceRecords");
                });

            modelBuilder.Entity("UniConnect.Domain.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentMileage")
                        .HasColumnType("integer");

                    b.Property<Guid>("FleetId")
                        .HasColumnType("uuid");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FleetId");

                    b.HasIndex("Vin")
                        .IsUnique();

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("UniConnect.Domain.Entities.VehicleLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Heading")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<decimal?>("SpeedKph")
                        .HasColumnType("numeric");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId", "RecordedAt");

                    b.ToTable("VehicleLocations");
                });

            modelBuilder.Entity("UniConnect.RoboTaxi.Entities.RoboTaxiProfile", b =>
                {
                    b.Property<Guid>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AutonomyLevel")
                        .HasColumnType("integer");

                    b.Property<int?>("BatteryPercent")
                        .HasColumnType("integer");

                    b.Property<int>("GroundedReason")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastDisengagementAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OperationalState")
                        .HasColumnType("integer");

                    b.Property<int>("PassengerCapacity")
                        .HasColumnType("integer");

                    b.Property<string>("SoftwareVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("VehicleId");

                    b.ToTable("RoboTaxiProfiles");
                });

            modelBuilder.Entity("UniConnect.Delivery.Entities.DeliveryAssignment", b =>
                {
                    b.HasOne("UniConnect.Delivery.Entities.DeliveryOrder", "DeliveryOrder")
                        .WithOne("Assignment")
                        .HasForeignKey("UniConnect.Delivery.Entities.DeliveryAssignment", "DeliveryOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeliveryOrder");
                });

            modelBuilder.Entity("UniConnect.Delivery.Entities.DeliveryOrder", b =>
                {
                    b.HasOne("UniConnect.Delivery.Entities.BusinessAccount", "BusinessAccount")
                        .WithMany()
                        .HasForeignKey("BusinessAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BusinessAccount");
                });

            modelBuilder.Entity("UniConnect.Domain.Entities.MaintenanceRecord", b =>
                {
                    b.HasOne("UniConnect.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("MaintenanceRecords")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("UniConnect.Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("UniConnect.Domain.Entities.Fleet", "Fleet")
                        .WithMany("Vehicles")
                        .HasForeignKey("FleetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fleet");
                });

            modelBuilder.Entity("UniConnect.Domain.Entities.VehicleLocation", b =>
                {
                    b.HasOne("UniConnect.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("Locations")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("UniConnect.Delivery.Entities.DeliveryOrder", b =>
                {
                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("UniConnect.Domain.Entities.Fleet", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("UniConnect.Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("Locations");

                    b.Navigation("MaintenanceRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
